import { expect, test } from '@playwright/test'
test('saves compressed photos, total item prices and manual currency conversion', async ({ page }) => {
  await page.goto('/app')
  await page.getByLabel('Seu nome').fill('Richard')
  await page.getByRole('button', { name: 'Vamos começar' }).click()
  await page.getByRole('button', { name: 'Nova lista' }).click()
  await page.getByLabel('Nome da lista').fill('Japão')
  await page.getByRole('combobox', { name: 'Moeda', exact: true }).selectOption('JPY')
  await page.getByText('Cotação manual (opcional)', { exact: true }).click()
  await page.getByRole('combobox', { name: 'Moeda secundária' }).selectOption('BRL')
  await page.getByLabel('1 JPY vale quantos BRL?').fill('0,035')
  await page.getByRole('button', { name: 'Criar lista', exact: true }).click()
  await page.getByRole('button', { name: 'Adicionar', exact: true }).click()
  await page.getByLabel('Nome do item').fill('Câmera')
  await page.getByLabel('Nome do item').press('Enter')
  await expect(page.getByLabel('Nome do item')).toHaveValue('')
  await page.getByRole('button', { name: 'Fechar', exact: true }).click()
  await page.getByRole('button', { name: 'Dispensar aviso' }).click()
  await page.getByRole('button', { name: 'Câmera', exact: true }).click()
  await page.getByLabel('Quantidade', { exact: true }).fill('2')
  await page.getByLabel('Preço planejado (JPY)').fill('10000')
  await page.getByLabel('Preço pago (JPY)').fill('9000')
  await page.getByLabel('Nota', { exact: true }).fill('Comprar em Akihabara')
  const data = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 2000; canvas.height = 1500
    const context = canvas.getContext('2d')
    if (context === null) throw new Error('Canvas unavailable')
    context.fillStyle = '#edb4c3'; context.fillRect(0, 0, canvas.width, canvas.height)
    return canvas.toDataURL('image/png').split(',')[1] ?? ''
  })
  await page.getByLabel('Foto opcional').setInputFiles({ name: 'camera.png', mimeType: 'image/png', buffer: Buffer.from(data, 'base64') })
  await expect(page.getByRole('button', { name: 'Salvar item' })).toBeEnabled()
  await page.getByRole('button', { name: 'Salvar item', exact: true }).click()
  await expect(page.getByText(/Planejado:.*10.000/)).toBeVisible()
  await page.reload()
  await expect(page.locator('[data-item-list] img')).toBeVisible()
  await page.getByRole('checkbox', { name: 'Comprar Câmera', exact: true }).click()
  await expect(page.getByText(/Pago ≈.*315,00/)).toBeVisible()
  await page.getByRole('button', { name: 'Desfazer', exact: true }).click()
  await expect(page.locator('[data-item-list] img')).toBeVisible()
})
