import { expect, test } from '@playwright/test'
test('creates, edits, archives, reactivates and deletes a list', async ({ page }) => {
  await page.goto('/app')
  await page.getByLabel('Seu nome').fill('Richard')
  await page.getByRole('button', { name: 'Vamos começar' }).click()
  await page.getByRole('button', { name: 'Nova lista' }).click()
  await page.getByLabel('Nome da lista').fill('Japão')
  await page.getByRole('button', { name: 'Usar 🇯🇵' }).click()
  await page.getByLabel('Moeda', { exact: true }).selectOption('JPY')
  await page.getByRole('button', { name: 'Criar lista', exact: true }).click()
  await expect(page.getByRole('heading', { name: '🇯🇵 Japão', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Opções da lista' }).click()
  await page.getByRole('button', { name: 'Editar lista' }).click()
  await page.getByLabel('Nome da lista').fill('Viagem ao Japão')
  await page.getByRole('button', { name: 'Salvar lista' }).click()
  await page.getByRole('button', { name: 'Opções da lista' }).click()
  await page.getByRole('button', { name: 'Arquivar lista' }).click()
  await expect(page.getByText('Lista arquivada', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Arquivo', exact: true }).click()
  await page.getByRole('link', { name: /Viagem ao Japão/ }).click()
  await page.getByRole('button', { name: 'Opções da lista' }).click()
  await page.getByRole('button', { name: 'Reativar lista' }).click()
  await page.getByRole('button', { name: 'Opções da lista' }).click()
  await page.getByRole('button', { name: 'Excluir lista', exact: true }).click()
  await page.getByRole('button', { name: 'Manter lista' }).click()
  await expect(page.getByRole('heading', { name: '🇯🇵 Viagem ao Japão', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Opções da lista' }).click()
  await page.getByRole('button', { name: 'Excluir lista', exact: true }).click()
  await page.getByRole('button', { name: 'Excluir definitivamente' }).click()
  await expect(page.getByRole('heading', { name: 'Sua próxima lista começa aqui.' })).toBeVisible()
})
