import { expect, test } from '@playwright/test'
test('persists theme, motion preferences and profile edits', async ({ page }) => {
  await page.goto('/app')
  await page.getByLabel('Seu nome').fill('Richard')
  await page.getByRole('button', { name: 'Vamos começar' }).click()
  await page.getByRole('link', { name: 'Ajustes', exact: true }).click()
  await page.getByText('Sakura', { exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'sakura')
  await page.getByLabel('Reduzir animações', { exact: true }).check()
  await expect(page.locator('html')).toHaveAttribute('data-reduced-motion', 'true')
  await page.getByLabel('Vibração sutil', { exact: true }).uncheck()
  await page.reload()
  await expect(page.getByLabel('Reduzir animações', { exact: true })).toBeChecked()
  await expect(page.getByLabel('Vibração sutil', { exact: true })).not.toBeChecked()
  await page.getByLabel('Vibração sutil', { exact: true }).focus()
  await page.keyboard.press(' ')
  await expect(page.getByLabel('Vibração sutil', { exact: true })).toBeChecked()
  await expect(page.getByLabel('Vibração sutil', { exact: true })).toBeFocused()
  await page.getByRole('radio', { name: 'Sakura' }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'night-cartoon')
  await expect(page.getByRole('radio', { name: 'Night Cartoon' })).toBeFocused()
  await page.getByText('Night Cartoon', { exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'night-cartoon')
  await page.getByRole('link', { name: /Seu perfil/ }).click()
  await page.getByLabel('Seu nome').fill('Richard Oliveira')
  await page.getByRole('button', { name: 'Salvar perfil', exact: true }).click()
  await page.getByRole('link', { name: 'Listas', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Olá, Richard Oliveira 👋' })).toBeVisible()
})
